version: "3.9"

services:
  app:
    image: maven:alpine
    working_dir: /app
    depends_on:
      - storage
    volumes:
      - ./soundrate:/app
    ports:
      - ${EXT_HTTP_PORT:-8080}:8080
    networks: ["soundrate-network"]
    command: >
      sh -c "
        apk add git &&
        git clone https://github.com/alex-massa/deezer-api.git &&
        mvn -f ./deezer-api/pom.xml &&
        rm -rf ./deezer-api &&
        mvn clean package verify tomee:run
      "
    environment:
      DATASOURCE_USER: ${DBMS_USER:-root}
      DATASOURCE_PASSWORD: ${DBMS_PASSWORD:-secret}
      DATASOURCE_DB: ${DBMS_DB}
      DATASOURCE_HOST: ${DBMS_HOSTNAME}
      DATASOURCE_PORT: 3306
      SMPT_HOST: ${SMTP_HOST}
      SMPT_PORT: ${SMTP_PORT}
      SMTP_STARTTLS: ${SMTP_STARTTLS:-true}
      SMPT_AUTH: ${SMTP_AUTH:-true}
      SMTP_EMAIL_ADDRESS: ${SMTP_EMAIL_ADDRESS}
      SMTP_EMAIL_PASSWORD: ${SMTP_EMAIL_PASSWORD}

  storage:
    image: mysql:debian
    container_name: ${DBMS_HOSTNAME}
    volumes:
      - soundrate-db:/var/lib/mysql
    ports:
      - ${EXT_DBMS_PORT:-3306}:3306
    networks: ["soundrate-network"]
    environment:
      MYSQL_USER: ${DBMS_USER:-root}
      MYSQL_PASSWORD: ${DBMS_PASSWORD:-secret}
      MYSQL_DATABASE: ${DBMS_DB}

volumes:
  soundrate-db:
networks:
  soundrate-network:
